### ISSUE TITLE
NameError: name 'habit' is not defined

### ISSUE THREAD

**Issue by lfq2333** [eshapard/AnkiHabitica#101]
Here is the issue. I have reinstall the add-on for several times. But it still shows up. Please help me fix it.

Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-02 11:39:11

Exception ignored in thread started by: <bound method Habitica.check_anki_habit_task of <1758045507.habitica_class.Habitica object at 0x000001AE6134BE80>>
Traceback (most recent call last):
  File "C:\Users\Feiqi\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 288, in check_anki_habit_task
    self.hrpg_showInfo("Your %s habit is not configured correctly yet.\nPlease set it to Up only and Mental attribute." % habit)
NameError: name 'habit' is not defined
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'

**Comment by 71e6fd52** [comment]
see #62
