### ISSUE TITLE
How to use python 3.6.8 instead of 3.8.0

### ISSUE THREAD

**Issue by halatony** [eshapard/AnkiHabitica#103]
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
    Platform: Mac 10.15.5
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-07-29 01:12:15
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Anki Habitica for 21 ['1758045507', 2020-03-24T16:28, 'None', mod]
    AwesomeTTS Google Cloud Text-to-Speech unofficial ['814349176', 2020-07-13T00:33, 'None', '']
    Enhance main window ['877182321', 2020-05-04T00:58, 'None', mod]
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T10:21, 'None', '']
    LPCG LyricsPoetry Cloze Generator ['2084557901', 2020-07-12T07:06, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155 1758045507 2084557901 814349176 877182321
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    
My habitca is not working on anki, errors every time. I downloaded python 3.6.8 but anki is not using it.

**Comment by 71e6fd52** [comment]
Why do you want to use python 3.6.8
