### ISSUE TITLE
Bug, help?

### ISSUE THREAD

**Issue by mavt88** [eshapard/AnkiHabitica#104]
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-16 21:32:29

Exception ignored in thread started by: <bound method Habitica.check_anki_habit_task of <1758045507.habitica_class.Habitica object at 0x000001C90243EFD0>>
Traceback (most recent call last):
  File "C:\Users\advto\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 288, in check_anki_habit_task
    self.hrpg_showInfo("Your %s habit is not configured correctly yet.\nPlease set it to Up only and Mental attribute." % habit)
NameError: name 'habit' is not defined
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'

**Comment by mavt88** [comment]
Now is it:

Erro 
Ocorreu um erro. Por favor, inicialize Anki enquanto segura a tecla SHIFT, isto vai desabilitar temporariamente os complementos (add-ons) que você instalou. 
Se o problema ocorre somente quando os complementos estão habilitados, por favor vá para Ferramentas > Complementos e desabilite algum(s) complemento(s), para descobrir qual complemento é o responsável pelo problema. 
Assim que você descobrir o complemento responsável, por favor relate o problema na seção de complementos em nossa página de ajuda. 
Informação de Debug:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-16 21:32:29

Exception ignored in thread started by: <bound method Habitica.check_anki_habit_task of <1758045507.habitica_class.Habitica object at 0x0000026F12A34E80>>
Traceback (most recent call last):
  File "C:\Users\advto\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 288, in check_anki_habit_task
    self.hrpg_showInfo("Your %s habit is not configured correctly yet.\nPlease set it to Up only and Mental attribute." % habit)
NameError: name 'habit' is not defined
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'

**Comment by 71e6fd52** [comment]
> In Habitica, you could try deleting your "Anki Points" habit (which is where AnkiHabitica tracks which reviews have been scored). The addon should create a new one.
https://github.com/eshapard/AnkiHabitica/issues/62#issuecomment-368843159
