### ISSUE TITLE
Massive Catalina conflicts

### ISSUE THREAD

**Issue by scottynorris** [eshapard/AnkiHabitica#106]
So the problem, no syncing. No warnings etc until I ran "score habitica backlog".

Then I followed [this](https://github.com/wilddom/memrise2anki-extension/issues/68#issuecomment-465673375) thread to install the matching version of Python with Anki.

The error disappeared, but still no update to habitica.

I realised my terminal was using the wrong version of python. So I switched it to 3.8.6 - still no luck.

I don't know where to go from here.

I'm using Catalina  10.15.7

**Comment by 71e6fd52** [comment]
Did the progress bar show on the study screen

**Comment by scottynorris** [comment]
Yes it did within Anki, but after messing around with Python (I think) has since disappeared

**Comment by 71e6fd52** [comment]
Try to reinstall AnkiHabitica and setup again

**Comment by scottynorris** [comment]
Actually, I just tried on the desktop version. It's still there, but it's not on my Ankidroid anymore. 

<img width="1680" alt="Screenshot 2020-11-07 at 16 14 59" src="https://user-images.githubusercontent.com/12828443/98436246-d87c0100-2114-11eb-9946-1f31430b8dc9.png">

**Comment by scottynorris** [comment]
Reinstalled, it updated 58 points to habitica. On habitica I checked, this worked. 

However when I complete a flashcard and sync Anki it doesn't update Habitica.

Restarting Habitica, it also did not update this one flashcard score.

**Comment by 71e6fd52** [comment]
The addon won't score each card. It will score every 12 card in default, which can be set by `sched` in addon config.

Ankidroid related see https://github.com/eshapard/AnkiHabitica#how-can-i-use-ankihabitica-in-ankidroid

**Comment by scottynorris** [comment]
Good to know, thanks.

I completed flashcards on phone, opened Anki desktop, synced 84 flashcards. Nothing happened. 

Had to manually go in and select score habitica backlog. Is this expected behaviour too?

**Comment by 71e6fd52** [comment]
> Had to manually go in and select score habitica backlog. Is this expected behaviour too?

No, it shouldn't happend. I am going to find out how to fix it.

**Comment by eshapard** [comment]
I think this is the expected behavior. I haven't used or looked at the 
code in a long time, but from what I remember, I don't think I 
programmed it to automatically check for backlogs after syncing... you 
have to either do some reviews on the desktop in order to get the 
scoring functions to run, or run the score backlog function.

Excerpts from 71e6fd52's message of November 7, 2020 4:58 am:

**Comment by scottynorris** [comment]
Could I be so bold as to suggest adding the Ankidroid information to the [home](https://github.com/eshapard/AnkiHabitica/wiki)? 

Maybe with the additional information something like:

"If you use Ankidroid you will need to sync your desktop version of Anki with Habitica. To do this, simple access the Tools menu from Anki desktop. Then go to AnkiHabitica > Score Habitica Backlog. The default settings will score every 12 flashcards."

Now that I've got it working I can see this as a fantastic way to motivate. Thank you so much for your time and energy on the project!

**Comment by 71e6fd52** [comment]
@eshapard I mistakenly assumed that the time when the hook "profileLoaded" was triggered has changed. But this behavier is strange. I can easlily change this by new hook sync_did_finish.
