### ISSUE TITLE
Offline points

### ISSUE THREAD

**Issue by EctoOctopus** [eshapard/AnkiHabitica#11]
Is there a way to turn of the real time sync? I would like to save all the points an upload them later, like it was before. I don't have constant internet access and it's impossible to study when the plugin has to check every time if i have an internet connection

**Comment by eshapard** [comment]
For that, you would need to use the older version. It's still posted on github. Just replace the version you have now with an older one.

**Comment by eshapard** [comment]
You can also try the newest version AnkiHabitica v2.0. It will check your internet connection much less often.

**Comment by eshapard** [comment]
Anki Habitica v2.0 is officially launched. This addon handles internet connection issues much more gracefully. Also, you'll need to upgrade by mid-July because Habitica is moving to a new API and the older versions of the addon will stop working. https://ankiweb.net/shared/info/954979168
