### ISSUE TITLE
set up the same habitica account for multiple profiles

### ISSUE THREAD

**Issue by liutiming** [eshapard/AnkiHabitica#110]
I am using multiple profiles to selectively sync cards with AnkiDroid, but I realise habitica anki is only scoring for one profile (tried backlog too). Is there a solution for this? Happy to provide logs (not sure where to retrieve them at the moment)

**Comment by 71e6fd52** [comment]
what happens if you switch profile and backlog

**Comment by liutiming** [comment]
So it will only work on one profile and when I switch to another profile, the progress bar of habitica does not work, nor does scoring backlog.

**Comment by 71e6fd52** [comment]
You need to setup AnkiHabitica for each profile.

**Comment by liutiming** [comment]
yup i did that but still not working...
did it work for you?

**Comment by 71e6fd52** [comment]
Yes, it works for me.

Are you sure you switched to another profile and then ran `Ankihabitica > Setup` again?

**Comment by liutiming** [comment]
Yes I am sure. is there a log that I can share?

**Comment by 71e6fd52** [comment]
Check `%appdata%/Anki2/addons21/AnkiHabitica/user_files/AnkiHabitica.conf`, it should look like:
```
{"<profile1>": {"user": "<User ID>", "token": "<API Token>", "score": 0, "oldscore": 0, "habit_id": "...", "oldsched": 12}, "<profile2>": {"user": "<User ID>", "token": "<API Token>", "score": 0, "oldscore": 0, "habit_id": "...", "oldsched": 12}}
```

**Comment by liutiming** [comment]
thanks for letting me know! for some reason despite my setup for the first time the fields remained empty. so I 
1. deleted the old task
2. filled the field manually
3. set up again in anki 

and it worked. i suspect the second step may not be necessary as 3 will overwrite 2.

thank you!
