### ISSUE TITLE
Adjust Progress Bar Length?

### ISSUE THREAD

**Issue by viviann16** [eshapard/AnkiHabitica#111]
Would it be possible (or could you make it possible) to adjust the progress bar length? 

For example, the habit is checked off whenever I go through 12 cards, but I would like to adjust it to 20 cards to challenge myself. I have tried changing the text in the description of the Habit in Habitica, but as soon as I restart Anki and refresh the Habatica page, it goes back to 12, and my progress bar remains at 12.

Also, just want to say I deeply appreciate and LOVE this add-on for Anki! Makes it much more enjoyable for me and I really needed this for motivation to go through my cards every day. It would be cool if I had the option to set this as a "daily" in Habitica too.

**Comment by 71e6fd52** [comment]
Changing `sched` to 20 in the addon setting can help you.

**Comment by 71e6fd52** [comment]
For daily habitica, there is some old code at https://github.com/eshapard/AnkiHabitica/blob/anki2.0/extras/daily_habit.py. If you know python, you can find out how to use this code (and pr to us).
