### ISSUE TITLE
Habitica anki reviews when not on internet 

### ISSUE THREAD

**Issue by Playandstudy** [eshapard/AnkiHabitica#112]
Hi,

I used Anki without internet yesterday and did around 848 reviews. When I opened Anki today morning (on internet), a message to sync my reviews with Habitica appeared, which I did. 
After that, I coudn't review my cards - there was no error message. Just that when the first card opened, and I clicked on 'show answer', the interface did not change, i.e. it kept on showing the front side of the card. 
On closing Anki again, and reopening it, another Habitica popup showed to sync my reviews. This kept on happening for 8-9 times.

Is this a bug?

**Comment by 71e6fd52** [comment]
Does a window with 'Scoring points' appear after agreeing to sync? If so then it is expected that Anki will not respond when this window appears. see #78, #105
