### ISSUE TITLE
Anki error

### ISSUE THREAD

**Issue by Charlie3217** [eshapard/AnkiHabitica#113]
My anki keeps crashing when I restart with the add on, I have to delete the add on and then re-add it to get the Habitica bar to show up, Then the next time I use anki I crash upon opening until I disable all my add ons.

**Comment by 71e6fd52** [comment]
What's the error message.

**Comment by pierceh25** [comment]
This has been happening for me as well. I would try to open it and then it would start opening, and then just disappears as if I never opened it. There hasn't been any message coming up in those instances. When I try to open it again after a crash, I get a notification that it's already running, but when I check my task manager it isn't running there either.
