### ISSUE TITLE
Interrupts and connection problems

### ISSUE THREAD

**Issue by AnomalousG** [eshapard/AnkiHabitica#12]
Greetings.

First, let me thank you for creating this helpful Anki addon. It's fun. 

Here is my feedback.

_EDIT: I've installed version 2.0. The popup screen now has an icon and shows the user's current Habitica stats. With those changes, do you think a solution to the popup interruptions could be to make the addon run in its own separate window that stays open alongside the main window and does not interrupt user interaction with the quiz, in any way? That way, the user won't have to click to close popups, and connection problems would not disrupt the rhythm of or interaction with the quiz. If a connection cannot be made with the Habitica server, for whatever reason, it would just show a cannot connect to server message, icon, or whatever message is returned by the Habitica API._

~~The recent update, the one that shows the points gained throughout the progress of a quiz, is a very good idea. I like having the progress visible as it is. However, the popup box is a bit disruptive. It interrupts the flow, and eventually becomes annoying. Do you think it would be less disruptive to have aggregate view of the points gained appear to the right of or instead of the bar, as in +15 XP  +3 G  +0 M, with the labels being a different color from the values? And, would it then be simpler to send those points all at once, at the end of the deck or when one leaves a deck instead of intermittently?~~

Secondly, yesterday, Habitica went down for maintenance. During that time, after completing every 5 or so cards, there was an attempt to send data to the website. Of course, the API was inactive, so it couldn't work. That prevented me from continuing with the decks. I had remove AnkiHRPG from the addon folder to be able to continue. The fact that Habitica API being down affected users' ability to complete their decks without hindrance, in my opinion, suggests that the intermittent sending of points may not be the best approach. I have no idea what to do about that, though. Hoping you do.

Thanks for your time and efforts.

**Comment by AnomalousG** [comment]
Original post edited.

**Comment by eshapard** [comment]
I'm working on a new version that handles bad connections and down for
maint. better.

In the meantime, I believe the version you have has all the config
variables at the top of the file. You can set a larger reward schedule so
you see the pop-up less often. Also, the old version is still in github if
you decide you prefer it.

**Comment by eshapard** [comment]
Also, you use the space bar and number keys to select the buttons in anki right? Just hit the space-bar when the pop-up shows. That will close it.

**Comment by eshapard** [comment]
Version 2.0 of the Anki Habitica add-on was just published. Time to upgrade... https://ankiweb.net/shared/info/954979168
