### ISSUE TITLE
Spurious points being scored

### ISSUE THREAD

**Issue by MosheSteinberg** [eshapard/AnkiHabitica#120]
I recently moved across to the latest version of anki habitica and now, whenever I load anki, even though I have done no reviews, habitica pops up saying it is scoring 71 points to habitica

This is my config:
```
{
    "auto_earn": true,
    "barbgcolor": "#BFBFBF",
    "barcolor": "#603960",
    "check_db_on_profile_load": true,
    "debug": false,
    "deckpoints": 0,
    "download_avatar": false,
    "habit": "Anki Points",
    "keep_log": false,
    "learned_eq": 2,
    "matured_eq": 2,
    "proxy": "",
    "sched": 18,
    "show_mini_stats": true,
    "show_popup": false,
    "show_progress_bar": true,
    "step": 1,
    "timeboxpoints": 1,
    "tries_eq": 2
}
```

**Comment by MosheSteinberg** [comment]
This may have been solved by completely uninstalling and reinstalling the add in

**Comment by 71e6fd52** [comment]
AnkiHabitica will check *all* your unsynced score even on the device that AnkiHabitica didn't be installed on, and will keep asking you until you score them.

**Comment by MosheSteinberg** [comment]
@71e6fd52 that was not the issue. I had done no reviews on any of my devices, yet it was 'scoring 71 points to Habitica' every time I opened Anki desktop app.

**Comment by MosheSteinberg** [comment]
A complete uninstall and reinstall of ankiHabitica has solved this issue
