### ISSUE TITLE
Habitica not scoring certain Anki function 

### ISSUE THREAD

**Issue by Habiticanki** [eshapard/AnkiHabitica#125]
Habitica is scoring my normal decks but as soon as I make a custom study session of a deck with all Review cards in random order the add on stops scoring my cards! Please help as the custom study session is my main way of studying anki

**Comment by 71e6fd52** [comment]
Can't be reproduced. Did the progress bar show up?

**Comment by Habiticanki** [comment]
yes the progress bar shows up but the bar just doesn't fill up during custom study sessions, it fills up normally during regular deck study

**Comment by 71e6fd52** [comment]
Did you tick the option "Reschedule cards based on my answers in this deck" in the options of the filtered deck? if so, Anki will not write your answer to the database. This addon needs the data written in the database to work.

**Comment by Habiticanki** [comment]
I do custom study session> then study by card state or tag> then all cards in random order( don't reschedule) , it used to work before for the last year, it just stopped working a week ago

**Comment by 71e6fd52** [comment]
I have not idea why it used to work, since the addon have not update in five month.

**Comment by 71e6fd52** [comment]
You say it just stopped working a week ago, but the addon hasn't update for 5 months. I have no idea why it works before.
