### ISSUE TITLE
Config values for "learned_eq" "mature_eq" and "tries_eq" don't do anything. I get 1 tick on progbar every card.

### ISSUE THREAD

**Issue by carlos1172** [eshapard/AnkiHabitica#126]
Hello,

I tried this with 2.1.49, with all other addons disabled, and it seems these three values don't work. I set them to ridiculous values like 30, so it should only tick once every 30 cards, and it still ticked once per card I did. Sometimes it ticks two per card.

**Comment by eshapard** [comment]
These three settings (learned_eq, mature_eq, and tries_eq) only affect 
newly learned cards, mature cards, and incorrect answers; they won't 
affect successful reviews of non-mature cards. "mature" meaning that 
cards have an interval of > 20 days.

From your post, I'm not sure if you accounted for that.

Try setting the 'sched' and 'step' to different values. "Sched" is how 
many points you have to score in Anki before the addon gives you a score 
on Habitica. "Step" is the size of the ticks on the progress bar. 
"Sched" should be a multiple of "sched".

The default values are 'sched' = 12; meaning Habitica is scored after 
you earn 12 points in Anki. And step = 1; meaning you see a tick on the 
progress bar for each point earned. The *_eq settings can cause you to 
earn more than one point for a successful answer.

Try setting 'sched' to something like 48 and 'step' to 4.

https://github.com/eshapard/AnkiHabitica/wiki

Excerpts from carlos1172's message of November 4, 2021 1:30 am:

**Comment by carlos1172** [comment]
Thank you for getting back to me, I will try and play around with it more, but I think you're right and I am mistaken. Apologies.
