### ISSUE TITLE
Upgrade Habitica API from version 2 -> 3

### ISSUE THREAD

**Issue by crookedneighbor** [eshapard/AnkiHabitica#13]
Version 2 of the Habitica API will be officially [deactivated on July 15th](http://devs.habitica.com/api-v2-deprecation-notice/). 

[Here is a migration guide](http://devs.habitica.com/api-v2-v3-migration-guide/) for upgrading to version 3. If you have any questions, feel free to reach out on [Github](https://github.com/HabitRPG/habitrpg/issues) or the [Aspiring Comrades Guild](https://habitica.com/#/options/groups/guilds/2ff9822b-27f2-4774-98da-db349b57a38e).

**Comment by eshapard** [comment]
Thanks! hopefully I can make the change before the cutoff date.

**Comment by eshapard** [comment]
Thank you. Version 2.0 was just released with support for API v3.
