### ISSUE TITLE
Your User ID or API Token is incorrect, please setup again with correct infomation.

### ISSUE THREAD

**Issue by bootymcjudy** [eshapard/AnkiHabitica#132]
I'm not sure of this is a dumb question, but I am running my own/self-hosted instance of Habitica and using the User ID and API Token from there.

`Your User ID or API Token is incorrect, please setup again with correct infomation.`

Does this not work for a selfhosted instance of Habitica?

**Comment by Blauelf** [comment]
[habitica_api.py](https://github.com/eshapard/AnkiHabitica/blob/master/AnkiHabitica/habitica_api.py) mentions habitica.com in two places of the code, I assume if you go self-hosted habitica, you'd have to replace those two with your own server name.

**Comment by bootymcjudy** [comment]
Thank you! it works! :D
