### ISSUE TITLE
Anki ignoring points

### ISSUE THREAD

**Issue by FlamingoChunguita** [eshapard/AnkiHabitica#134]
Hello! First of all, thank you for this great add-on :)

I've encountered an issue when syncing progress between devices. If I answer the cards needed to complete a progress bar in Ankidroid, upon syncing in my computer, I will get the backlog prompt to score the habit, but all my progress towards the next bar will be ignored. Basically anki seems to round down the number of cards I've answered to the nearest number of habit score, causing me to lose progress. Am I doing something wrong?

**Comment by 71e6fd52** [comment]
This is expected behavior, and synchronizing from Ankidroid is not the same method as using AnkiHabitica on a pc. While it is not completely impossible to record exact numbers, it may complicate the code.
