### ISSUE TITLE
Anki Crashing Due to Anki Habitica 21

### ISSUE THREAD

**Issue by melistarrgwa** [eshapard/AnkiHabitica#137]
For whatever reason, even though it was working fine for the first week, anki has started crashing on opening with this addon. I went through and found that this is the culprit, but deleting and redownloading just created the same issue. Here is my error report. 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.5.2-arm64-arm-64bit
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2023-10-23 23:10:10

failed to open '/var/folders/v_/jbqk26n566q9h90c0my1fm1w0000gn/T/discord-ipc-0': [Errno 61] Connection refused

let me know if you need more info I'm new to github

**Comment by 71e6fd52** [comment]
This addon does nothing on `discord-ipc`. This error does not appear to be caused by AnkiHabitica. Do you try to disable all other addons and keep only AnkiHabitica enabled?
