### ISSUE TITLE
Score backlog not setting new recounting reviews

### ISSUE THREAD

**Issue by twilsonco** [eshapard/AnkiHabitica#16]
Steps to reproduce:

1. Perform reviews on another device and sync
2. Open Anki 2.0 and sync
3. Perform manual backlog sync with AnkiHabitica
4. Sync, log out and back into profile and sync again
5. Perform manual backlog again
Expected behavior: No reviews will be found by the backlog sync and a dialog will say as much
Actual behavior: The same number of points scored on Habitica in (3) will be scored again in (5).
Note that if you perform (5) without first logging out/in (4) then no reviews will be found, as expected.

Simple fix may be to update the Habitica note at the end of score_backlog(). I'll give that a shot.

**Comment by twilsonco** [comment]
This issue is solved by commit 534a2f1e51ee772c30052746775bd0c36fc163e5.

**Comment by eshapard** [comment]
I see. I use the desktop a lot, so I didn't notice this. Your solution
fixed it right?

**Comment by twilsonco** [comment]
Yeah, the problem is resolved. This involves updating the habitica habit note, which could result in reviews not being counted if a user has poor syncing habits when using Anki, but the user is warned before a backlog sync occurs that they need to have Anki synced across their devices before continuing, so the loss of reviews should be minimal.
