### ISSUE TITLE
The add-on "AnkiHabitica" has the mistake.what should I do?

### ISSUE THREAD

**Issue by StacyZD** [eshapard/AnkiHabitica#21]
I  have installed the add-on "AnkiHabitica" many times.But the problem still exists. There is something that we need to  notice. I can use the Anki formally beside the software often stuck , even though it remind me there are something wrong . I need your help very much . I hope you can reply soon.
![default](https://cloud.githubusercontent.com/assets/21984987/18231172/d7bbda9e-72e3-11e6-8c19-0cdd46cbbd0e.PNG)

**Comment by eshapard** [comment]
OK. The problem is that ankihabitica can only handle profile names that are
simple ASCII text. I'm guessing your Anki profile name uses Unicode. I'll
try to fix this in a future release.

**Comment by junsuwhy** [comment]
I also met this problem. 

> 附加元件出現錯誤
> 請到附加元件的論壇上回報此問題：
> https://anki.tenderapp.com/discussions/add-ons
> 
> Traceback (most recent call last):
>   File "aqt/progress.pyc", line 69, in handler
>   File "aqt/main.pyc", line 110, in setupProfile
>   File "aqt/main.pyc", line 244, in loadProfile
>   File "anki/hooks.pyc", line 26, in runHook
>   File "/Users/mac/Documents/Anki/addons/ankihabitica.py", line 693, in grab_profile
>     ah.settings.profile = str(aqt.mw.pm.name)
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

Thanks.

**Comment by wapgod** [comment]
I also met this problem, and thanks for your add-on

**Comment by eshapard** [comment]
No fix yet. Just use a profile name in plain ASCII if you want to use the
addon

**Comment by eshapard** [comment]
user aleadag has fixed this for us. I haven't tested it myself, but it looks good. Download the new version of the addon from github.
