### ISSUE TITLE
Keep getting Error

### ISSUE THREAD

**Issue by chacotanlines** [eshapard/AnkiHabitica#26]
I followed every thing and even tried to manually install it but I keep getting the same error:

Traceback (most recent call last): File "aqt/progress.pyc", line 69, in handler File "aqt/main.pyc", line 110, in setupProfile File "aqt/main.pyc", line 244, in loadProfile File "anki/hooks.pyc", line 26, in runHook File "/Users/TABBYCAT/Documents/Anki/addons/ankihabitica.py", line 701, in grab_profile if ah.settings.check_db_on_profile_load and ah.settings.configured and ah.habitica.grab_scorecounter('Anki Points') and compare_score_to_db(): File "/Users/TABBYCAT/Documents/Anki/addons/AnkiHabitica/habitica_class.py", line 332, in grab_scorecounter if self.missing[habit]: KeyError: 'Anki Points'

i also get a habit added in habitica that is called "anki points" and in the notes it has {"scorecount": 0, "sched": 12, "scoresincedate": 1476796680}

Please help!

**Comment by chacotanlines** [comment]
Also thank you for doing this! It means a lot!

**Comment by eshapard** [comment]
Try ignoring the error for now and work through some cards. Do you see the
progress bar advancing? Any progress bar at all? What happens when it gets
to the end?

**Comment by chacotanlines** [comment]
I'll go to a place that has wifi and then get back to you. Do you need wifi for the Habitica add on to work?

**Comment by eshapard** [comment]
Yes and no... it tolerates not having a connection, but for everything to
work as advertised, you need to be able to contact habitica.

**Comment by chacotanlines** [comment]
When using the computer with internet connection, it works fine. When I don't have the internet, it says that it will save my points for later, but when I turn the internet back on and score the backlog, it tells me there is no backlog. So I'm confused about this.  Also I have no idea how to use this program on ankimobile for iPhone. 

I don't have the internet at home so the majority of my time is spent not having internet connection. What are some tips and tricks to use anki without internet, but still get credit for it when I go to school or the library with internet?

**Comment by eshapard** [comment]
You can't use the addon on a mobile phone, but it should pick up any points
from mobile devices as long as you have synced everything with ankiweb
first.

RE not having a backlog, there are two things that might be happening: 1.)
During normal use, the addon will score several points at a time to try
prevent a backlog from forming or to whittle away at one that has already
formed.. 2.) When you start Anki, the addon automatically prompts you to
score the backlog.

I haven't noticed any problems with internet going down/up etc. and losing
points.
