### ISSUE TITLE
Option to disable counting of points during review?

### ISSUE THREAD

**Issue by smh020** [eshapard/AnkiHabitica#35]
I find that the add-on has improved in how long it takes to count up, but there still is a second delay when pressing a review button. 

I do know that this is difficult if not impossible to change due to the way that it works, but a what could work really well is to disable counting within the reviews, and count the points on profile CLOSE or OPEN as in the option to score the backlog upon anki starting up and syncing. 

It could also be a good idea to have an option to have counting of points on the backlog on SYNC

**Comment by eshapard** [comment]
I'll keep that in mind. I do have some ideas for making the process faster during reviews. Essentially, the code could be changed so it scores points on application events (hooks), which is very fast, but only checks the database on profile open/close, or through the 'score Habitica backlog' option.

But this project is very much on the back-burner for me right now. If you want to try hacking it yourself, you can check out early versions of the addon; they used hooks only.

I've found that sync is actually a bad time to do anything, as the hooks for it are kind of messy and you don't want to mess with the sync process. Profle open/close is much better.
