### ISSUE TITLE
Is there a way to make it run faster?

### ISSUE THREAD

**Issue by JackElsey** [eshapard/AnkiHabitica#37]
This add-on is great, but it causes a small (<1 second) lag every time I review a card. I have about 15-20 decks, but I'd prefer not to consolidate them just to make an add-on run faster. I have `deckpoints` set to zero. Is there another way to make this add-on run faster?

**Comment by JackElsey** [comment]
Sorry, I didn't see the other identical issue: https://github.com/eshapard/AnkiHabitica/issues/27 

I'll close this out.

**Comment by eshapard** [comment]
Edit the ankihabitica.py file and change the settings that control scoring. Setting one of them to 0 will disable database checks for that item. That will speed things up for you.
