### ISSUE TITLE
Does not work on mobile devices separately?

### ISSUE THREAD

**Issue by lizyn** [eshapard/AnkiHabitica#38]
It's an innovative addon, but I've got some questions while using it.

The wiki says it can work on a mobile device. Does that mean you can just sync the score directly from AnkiMobile to Habitica or you just have to open the PC version of Anki and press "Store Habitica Backlog" after reviewing on a mobile device to finish the whole process? Thanks in advance.

**Comment by eshapard** [comment]
There are no addons for mobile versions of Anki, but the addon will find your mobile activity from looking at the data you sync with ankiweb. 

Sync AnkiMoble, then run Anki on PC, sync, and "Score Habitica Backlog"...

You can configure it to do this automatically on startup. I don't remember if it's set up that way by default or not.

**Comment by lizyn** [comment]
Thanks for your reply, it's still a good extension despite of that.
