### ISSUE TITLE
Can't not pull the Avatar 

### ISSUE THREAD

**Issue by quentin-chen** [eshapard/AnkiHabitica#39]
Every time when I start Anki, the error shows, the function is working well, but quite annoying.
macOS Sierra 10.12.4

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Unhandled exception in thread started by <bound method Habitica.save_avatar of <AnkiHabitica.habitica_class.Habitica object at 0x9e18df0>>
Traceback (most recent call last):
  File "/Users/kchen/Library/Application Support/Anki2/addons/AnkiHabitica/habitica_class.py", line 89, in save_avatar
    self.avatarfile = self.avatarfile.decode(sys.getfilesystemencoding())
  File "encodings/utf_8.pyc", line 16, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 67-68: ordinal not in range(128)

**Comment by eshapard** [comment]
Hmm... it looks like this is related to a unicode Anki profile, perhaps. Is your Anki Profile something other than User 1?

**Comment by quentin-chen** [comment]
Yes, my profile is Chinese characters '用户1' which means the same as 'user 1' but generated by Anki as default.

**Comment by eshapard** [comment]
OK, I thought we had fixed the unicode character issue, but maybe the fix doesn't work for everything.

Have you tried downloading the version on github? It's possible that I made a mistake and posted the wrong version to ankiweb.

If the version posted on github doesn't work, then the fastest work-around would be to just rename your profile to 'User 1'.

**Comment by quentin-chen** [comment]
I tried to download it from Github and overwritten the directory manually. But problem still existing.

Then, I changed the profile name to English as workaround, it work now.

**Comment by JGarros** [comment]
I renamed to User 1 and it worked! thanks!

**Comment by quentin-chen** [comment]
@eshapard it works~
