### ISSUE TITLE
How to make progress slower

### ISSUE THREAD

**Issue by wouterch** [eshapard/AnkiHabitica#40]
First of all, thanks for making this amazing integration between Anki and Habitica! My question is about making progress 'slower'. I'm learning a language and I feel that I get exp (and the accompanying pop-up saying so) way too often as I progress through my cards. I've tried editing the settings (like editing the steps, and the number of points you get for each card etc) but it doesn't seem to help. What's the fix for just making the progress bar progressing more slowly?

**Comment by eshapard** [comment]
edit ankihabitica.py

change sched to a larger number (try 100)
change step to a larger number (try 10)
