### ISSUE TITLE
Add a LICENSE.md file

### ISSUE THREAD

**Issue by picsi** [eshapard/AnkiHabitica#42]

**Comment by 71e6fd52** [comment]
@eshapard Why you leave this issue there, What's the license

**Comment by eshapard** [comment]
I released it as GPL, but I never got around to adding a license.md
file... so I never closed that issue.

Quoting 71e6fd52 (2019-06-04 20:36:20)

**Comment by 71e6fd52** [comment]
715177d

**Comment by eshapard** [comment]
I don't think a licence.md file is actually necessary, I think the code
itself mentions that it's released under the Gnu Public Licence. That's
probably good enough... it's not like I'm going to sue someone or
anything ;-)

Quoting 71e6fd52 (2019-06-04 20:36:20)

**Comment by 71e6fd52** [comment]
More clear and standard :)
