### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wapgod** [eshapard/AnkiHabitica#45]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Unhandled exception in thread started by <bound method Habitica.save_avatar of <AnkiHabitica.habitica_class.Habitica object at 0xee853f0>>
Traceback (most recent call last):
  File "/Users/robert/Library/Application Support/Anki2/addons/AnkiHabitica/habitica_class.py", line 89, in save_avatar
    self.avatarfile = self.avatarfile.decode(sys.getfilesystemencoding())
  File "encodings/utf_8.pyc", line 16, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 68-69: ordinal not in range(128)

**Comment by eshapard** [comment]
I made some changes to the version on github. Hopefully, this will fix the problem.

The addon had trouble saving the avatar image using Chinese characters, so I changed it to use the habitica user ID instead of the profile name.
