### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zbttl** [eshapard/AnkiHabitica#48]
When I install this add-ons and then restarted Anki,it called me

"一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons
Traceback (most recent call last):
Unhandled exception in thread started by <bound method Habitica.save_avatar of <AnkiHabitica.habitica_class.Habitica object at 0x04100070>>  File "aqt\progress.py", line 69, in handler
  File "aqt\main.py", line 110, in setupProfile
  File "aqt\main.py", line 244, in loadProfile
  File "anki\hooks.py", line 26, in runHook
  File "C:\Users\zbttl\AppData\Roaming\Anki2\addons\ankihabitica.py", line 717, in grab_profile
    if ah.settings.check_db_on_profile_load and ah.settings.configured and ah.habitica.grab_scorecounter('Anki Points') and compare_score_to_db():
  File "C:\Users\zbttl\AppData\Roaming\Anki2\addons\AnkiHabitica\habitica_class.py", line 332, in grab_scorecounter
    if self.missing[habit]: 
KeyError: 'Anki Points'"

and then I closed and restarted Anki again,it called me,

"发生了一个错误。 它可能是由一个无害的漏洞造成的， 
或者你的记忆库可能有一个问题。 
为了确认这不是你的记忆库导致的问题，请运行 工具 > 检查数据库. 
如果这不能修复这个错误，请把下列信息复制到
漏洞报告窗口:
Unhandled exception in thread started by <bound method Habitica.save_avatar of <AnkiHabitica.habitica_class.Habitica object at 0x041FC170>>"

then I try to restart Anki many times.it always pop-up warnings same as the second warning,but the last
number ("0x041FC170") is different.
And I can still study deck by anki but it couldn't score my anki points on habitica.
I try to use my another computer but I get the same result.
All of my computers running on the Windows10.
I'm a Chinese college student and my English is bad,I hope you can understand.
Thank you.

**Comment by eshapard** [comment]
I made some changes to the version on github. Hopefully, this will fix the problem.

The addon had trouble saving the avatar image using Chinese characters, so I changed it to use the habitica user ID instead of the profile name.
