### ISSUE TITLE
Problem with anki points

### ISSUE THREAD

**Issue by ThomasH96** [eshapard/AnkiHabitica#50]
Hi,
I have a problem with scoring my Anki points. Every time i complete the progress bar i get the pop up which tells me i earned points. But it also says it couldn't score my Anki points on Habitica, followed with "Don't worry. I'll remember your points and try again later".
Restarting Anki or completing another progress bar doesn't help. Also my internet connection is working, and i have refreshed Habitica more than once. I hope you can help me, as this seems a very promising add on to me.

**Comment by eshapard** [comment]
please see other thread on github

**Comment by ThomasH96** [comment]
I can't seem to find the thread you are reffering to? The addon created a task in Habitica, but everytime it wants to give points to it, it just doesn't receive any points...

**Comment by jhouser** [comment]
I'm having this same issue. Looks like someone left a review on the Anki extensions page with the same deal as well. Complains while reviewing that the addon couldn't score points and will try later. Upon restarting Anki, it offers to sync points but that also fails silently. 

Anything else I can do to get you debug information?

**Comment by eshapard** [comment]
See other thread. Download version on github.

**Comment by eshapard** [comment]
https://github.com/eshapard/AnkiHabitica/issues/47
