### ISSUE TITLE
No change to Habatica account when Anki cards are done

### ISSUE THREAD

**Issue by NK3333** [eshapard/AnkiHabitica#51]
Hi,

I downloaded the add-on so my progress in Anki shows up in Habatica, but after putting in my API User ID and API Token, nothing seems to have changed. Anki now shows a progress bar, but when it fills up, it says I've earned points and they can't be uploaded yet so it will "try again later." I manually made my desktop Anki sync to Anki Web and then I headed over to my Habatica account (on the Habatica website) and manually made it sync, too, but no points show up. It does have a habit made called "Anki Points" but it never increases or shows any indication that I've done any work in Anki. 

Have I made a mistake in setting Anki/Habatica up?

**Comment by eshapard** [comment]
See issue #47 
https://github.com/eshapard/AnkiHabitica/issues/47

**Comment by NK3333** [comment]
Hi,

I downloaded the files in the v2.0 folder as mentioned on the thread for case #47 and extracted the zipped files into the Anki add on folder, but it doesn’t seem to have done anything. I still get the following message when I’m doing cards:

[cid:image003.png@01D3139C.6DFF9A50]
This is what my add-on file currently looks like:
[cid:image005.png@01D3139C.6DFF9A50]

I’m not familiar at all with coding, so please have some patience with me. What can I do to fix the issue?

Thank you so much for your help.
Sincerely,
Noreen Khan
