### ISSUE TITLE
progress bar shows has wrong number of ticks on custom settings

### ISSUE THREAD

**Issue by xavras** [eshapard/AnkiHabitica#54]
I changed settings to have 30 points to score on Habitica and 2 points on 1 progress bar tick. So should be 15 ticks on progress bar. But it's not - I've got 18. Everything else work fine - still scoring after reaching 15 ticks (30 points). It's suprisingly annoying. Any chance to fix it quickly?

My settings:

############### YOU MAY EDIT THESE SETTINGS ###############
    sched = 30                  #score habitica when this number of points is reached
    step = 2                    #this is how many points each tick of the progress bar represents
    tries_eq = 5                #this many wrong answers gives us one point
    barcolor = '#603960'        #progress bar highlight color
    barbgcolor = '#BFBFBF'      #progress bar background color
    timeboxpoints = 1           #points earned for each 15 min 'timebox'
    matured_eq = 2              #this many matured cards gives us one point
    learned_eq = 2              #this many newly learned cards gives us one point
    deckpoints = 0             #points earned for clearing a deck; Default = 0; WARNING: many decks = very slow!
    show_mini_stats = True      #Show Habitica HP, XP, and MP %s next to prog bar
    show_popup = True           #show a popup window when you score points.
    check_db_on_profile_load = True #check Anki database on profile load to see if there are unsynced reviews and sync if there are
    keep_log = False             #log activity to file
    ############# END USER CONFIGURABLE SETTINGS #############

**Comment by xavras** [comment]
Ok, I see how it's implemented. So the bug isn't length (18 = 15 *1,2), but skipping 3 or 4 last ticks in progress bar. I guess because of int value of progress (always 1 rectangle) -> error accumulating every time.

I made quick fix by myself: fake_length = real_length. But idea of quicker gained points after 80% is great so I will wait for any update :)

**Comment by eshapard** [comment]
Not a bug. That's how we achieve the illusion of faster progress after 80%;
by making the progress bar longer and advancing the shaded area more
quickly.

**Comment by xavras** [comment]
Yeah, I understand that. But what I read in description " After the bar reaches about 80%, it will progress twice as fast as it normally does." doesn't happen. It reaches 14 of 18 levels of progress bar normally - each 2 my good answers give 1 tick. And just skips suddenly to the end after that. So when I changed code to not faking length (so it has 15 elements), then progress bar works like normal one, without any feature. You can check it out yourself with my settings. It doesn't advance 2x quicker after reaching 80% of progress - so it reach only 15 of 18 elements before sending point to Habitica. And this I consider is a bug.
Thanks for response :)

**Comment by eshapard** [comment]
New Bugs should be opened in a new thread.

I'll start a new one for you...

**Comment by eshapard** [comment]
See new thread: https://github.com/eshapard/AnkiHabitica/issues/55
