### ISSUE TITLE
Bar length not increasing correctly with step > 1

### ISSUE THREAD

**Issue by eshapard** [eshapard/AnkiHabitica#55]
> After the bar reaches about 80%, it will progress twice as fast as it normally does." doesn't happen. It reaches 14 of 18 levels of progress bar normally - each 2 my good answers give 1 tick. And just skips suddenly to the end after that. 

This seems to be because the code was not tested much with step > 1

Will adjust make_habit_progbar function to try to account for this.

**Comment by xavras** [comment]
Seems working now. One more thing - it always make progress on 'step' value of good answers. So if i have step = 2 and reach 80% then after 1st good answer nothing happen. And after 2nd it sets 2 ticks at once. Intuitively progress should be 2x faster, so with 2x less good answers. But it's not really bothering tbh.
I don't know if you've ever considered 'solid' progress bar. I think it should work better - visual feedback is immediate no matter what setting you have. And such problems wouldn't exist.
And sorry again for mention multiple things in one thread. Fix for bug looks like working :) Thanks for help.

**Comment by eshapard** [comment]
I did consider a more granular approach, but it would be much harder to
implement, and the benefit just doesn't outweigh the increased complexity
in my opinion.
