### ISSUE TITLE
Error when earning points

### ISSUE THREAD

**Issue by DreamFlasher** [eshapard/AnkiHabitica#58]
When earning points I receive this error:
![image](https://user-images.githubusercontent.com/31695/32314426-27125458-bfa8-11e7-982a-7bad64874335.png)

**Comment by eshapard** [comment]
That's a problem habitica now has generating user avatars for download via
the API. The problem is on their end; not ours.

**Comment by eshapard** [comment]
Habitica has still not fixed this error. Changed addon to use a different image instead of trying to download the avatar.
