### ISSUE TITLE
Error when loading in Anki.

### ISSUE THREAD

**Issue by Joshua0921** [eshapard/AnkiHabitica#59]
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\progress.py", line 69, in handler
  File "aqt\main.py", line 110, in setupProfile
  File "aqt\main.py", line 244, in loadProfile
  File "anki\hooks.py", line 26, in runHook
  File "C:\Users\Wang\AppData\Roaming\Anki2\addons\ankihabitica.py", line 717, in grab_profile
    if ah.settings.check_db_on_profile_load and ah.settings.configured and ah.habitica.grab_scorecounter('Anki Points') and compare_score_to_db():
  File "C:\Users\Wang\AppData\Roaming\Anki2\addons\AnkiHabitica\habitica_class.py", line 332, in grab_scorecounter
    if self.missing[habit]: 
KeyError: 'Anki Points'

**Comment by erileff** [comment]
Same issue. I'd opened the edit part of the add-on, but didn't actually change anything. When reopening Anki, this happened.

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/progress.pyc", line 69, in handler
  File "aqt/main.pyc", line 110, in setupProfile
  File "aqt/main.pyc", line 244, in loadProfile
  File "anki/hooks.pyc", line 26, in runHook
  File "/Users/ericaleff/Library/Application Support/Anki2/addons/ankihabitica.py", line 717, in grab_profile
    if ah.settings.check_db_on_profile_load and ah.settings.configured and ah.habitica.grab_scorecounter('Anki Points') and compare_score_to_db():
  File "/Users/ericaleff/Library/Application Support/Anki2/addons/AnkiHabitica/habitica_class.py", line 332, in grab_scorecounter
    if self.missing[habit]: 
KeyError: 'Anki Points'

**Comment by eshapard** [comment]
Do you have a habitica habit called 'Anki Points'? If so, try deleting it
and restart Anki. Ignore the error if it pops up at first and do a few
minutes of card reviews. Then restart and see if it still pops up.

**Comment by haitike** [comment]
I have the same problem, and I tried the solution eshapard suggested but it didn't work.

When I do reviews after removing the habit and restarting i get the message "Hmmm, I can't connecto to Habitaca. Perhaps your interned is down". 

The "Anki Points" habit it is not recreated again. After that I tried to reinstall the addon (removing the credential folder) and it didn't work neither, same problem.

**Comment by Blauelf** [comment]
Sounds like a different problem, maybe on Habitica's side. I just successfully scored some points, does the problem still persist for you?

**Comment by haitike** [comment]
Yes. When Anki starts I get the same error than opp. And when I score I get the "I can't connect to Habitaca" error, so the habit is never recreated.

**Comment by haitike** [comment]
I deleted it and tried in a different computer and it worked. So I will use that computer for habitaca tracking.

Maybe it was a problem with the first computer.

**Comment by Blauelf** [comment]
@guischmo Which problem? This issue got used for different problems, first was habit "Anki Points" being inconsistent (which can often be fixed by deleting the habit and having it re-created), second was not being able to connect to Habitica, which without further information could be about anything (like certificate/encryption problems, your antivirus or firewall interfering, ...)

**Comment by guischmo** [comment]
It was both. I suspect the addon could never connect to habitica, i'll try with my own wifi when I get home

**Comment by eshapard** [comment]
Closing this issue. Please create a new issue with a descriptive subject instead of saying 'me too' to this one.
