### ISSUE TITLE
Key Error: 'Anki Points'

### ISSUE THREAD

**Issue by Scarletalexander** [eshapard/AnkiHabitica#62]
![img20180227113320](https://user-images.githubusercontent.com/35050146/36709745-740ba21a-1bb4-11e8-835f-581e24a98389.jpg)

**Comment by Blauelf** [comment]
In Habitica, you could try deleting your "Anki Points" habit (which is where AnkiHabitica tracks which reviews have been scored). The addon should create a new one.

**Comment by eshapard** [comment]
What Blauelf said. This is a fairly common problem. I think it's caused by installing the addon but then quickly restarting Anki before the addon is able to fully create the habitica habit.

**Comment by eshapard** [comment]
Blauelf, thanks for handling some of these error issue reports for
ankihabitica... much appreciated.
