### ISSUE TITLE
Invalid code, or add-on not available for your version of Anki

### ISSUE THREAD

**Issue by lalaithan** [eshapard/AnkiHabitica#65]
I get this error message when I put the add-on code in Anki. Currently using version 2.1.1 on Windows 10.

**Comment by Blauelf** [comment]
What's the add-on, and is it available for Anki 2.1?

**Comment by Blauelf** [comment]
Currently not available for Anki 2.1.

If you're into Python, you might try to convert it:
https://apps.ankiweb.net/docs/addons.html#porting-anki-2.0-add-ons

**Comment by zianggao** [comment]
我也希望能出2.1.

**Comment by zianggao** [comment]
I can't program, and my attempts to convert have been unsuccessful for a long time. Can you come up with a 2.1 version?

**Comment by zianggao** [comment]
I can't program, and my attempts to convert have been unsuccessful for a long time. Can you come up with a 2.1 version?

**Comment by eshapard** [comment]
2.1 version created by another user.
