### ISSUE TITLE
Unable to connect to Habitica

### ISSUE THREAD

**Issue by bigredjoe** [eshapard/AnkiHabitica#71]
On Anki 2.1: After installing, and filling the progress bar, I get this error message:
<img width="401" alt="Screen Shot 2019-05-27 at 1 23 36 PM" src="https://user-images.githubusercontent.com/145475/58434885-8f043700-8083-11e9-90f2-bd88946cf15a.png">

My computer is fully online and Habitica is up, it seems to be an issue with the the add-on.

**Comment by eshapard** [comment]
It's possible your userID / key are not correct. (they are NOT your username/password)
Did the addon create the Anki Points habit?

**Comment by bigredjoe** [comment]
Doubled checked and I don't think that is the problem. I have used the values I used in AnkiHabitica in other integrations that call the Habitica API.

**Comment by eshapard** [comment]
Sorry it's not working, I don't actually have Anki 2.1, so I can't do much troubleshooting.

The addon was ported to 2.1 by another user: https://github.com/71e6fd52/AnkiHabitica
I crossed my fingers and accepted his version without being able to test it out myself.

You might try deleting the Anki Points habit and letting the addon attempt to create it again.

Other than that, If you turn on the logging option (hopefully, it will work) we might get some clues as to what's going on.

Or you could try to contact 71e6fd52 by posting in one of the closed threads that he responded to.

**Comment by bigredjoe** [comment]
I figured out what the issue was: the add-on was swallowing an ssl cert error:
https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

I was able to resolved it by using the instructions here:
https://github.com/wilddom/memrise2anki-extension/issues/68#issuecomment-465673375

**Comment by eshapard** [comment]
Interesting... I may need to point other users to that link.

What OS are you using? The Windows versions come with their own little python engine (probably to make install simpler). I'm guessing you use a *nix-based system like me where Anki just uses your own python installation.

**Comment by bigredjoe** [comment]
Yes, I am using Mac OS. I think Anki uses your local python if it is a the right version. For the error I was getting, python needed a system wide way of validating the ssl cert for requests and the only way I know of doing that on Mac is to install the same version of python as Anki and run the script Install Certificates.command that comes with it.

**Comment by MedAnki** [comment]
> Yes, I am using Mac OS. I think Anki uses your local python if it is a the right version. For the error I was getting, python needed a system wide way of validating the ssl cert for requests and the only way I know of doing that on Mac is to install the same version of python as Anki and run the script Install Certificates.command that comes with it.

I tried using your method but it didn't work for me :(

**Comment by MedAnki** [comment]
https://github.com/eshapard/AnkiHabitica/issues/67#issuecomment-497289663
