### ISSUE TITLE
New Maintainer Wanted

### ISSUE THREAD

**Issue by eshapard** [eshapard/AnkiHabitica#73]
I am no-longer actively using Anki, or Habitica. Therefore, I don't have much interest in maintaining this project. This was a labor of love, and I'm not quite ready to abandon it, but I am interested in handing this project off to someone else.

So if you understand the code feel like taking over, let me know :-)

**Comment by 71e6fd52** [comment]
I can take over it, but could ankiweb transfer addon?

**Comment by eshapard** [comment]
@71e6fd52  Cool. I'll add you as a collaborator and you should then have access to push changes, etc. If that doesn't give you enough permissions, then I can transfer the project to you.

For ankiweb, I don't think we can transfer the addon. But what we can do is I'll keep my version 2.0 up and delete the file for Anki 2.1. I'll re-name the listing to AnkiHabitica for 2.0. Then you can set up a clone of the listing, but call it AnkiHabitica for 2.1 and post only the addon file for 2.1.

We can then just change the Readme.md file to have both codes; the addon code for 2.0 and the addon code for 2.1.

**Comment by 71e6fd52** [comment]
@eshapard Look like good. btw, what's the meaning of issue tag "reference"?

**Comment by eshapard** [comment]
I added that to 'issues' that I was keeping open just so other people
could find them.

For example, sometimes people install the addon, but don't give it time
to create the habit, or something. People have created several issues
with that same error message (mising key). Restarting Anki usually fixes
it.

I left some of those issues open in hopes that people would see the
troubleshooting steps instead of posting a duplicate issue. These are
mostly not problems with the addon; but common issues people have.

Quoting 71e6fd52 (2019-06-04 18:11:34)

**Comment by eshapard** [comment]
I see you posted the addon to your ankiweb account already.
I've added a link to the 2.0 version page https://ankiweb.net/shared/info/954979168

Unfortunately, there doesn't seem to be a way to delete the 2.1 addon from my account, but I've contacted admin to see if somebody (maybe Damien himself) can do that for me.

**Comment by 71e6fd52** [comment]
but it said "Only supports Anki 2.0.x." already (might admin done)

**Comment by 71e6fd52** [comment]
Why not delete notice in description and close the issue.

**Comment by eshapard** [comment]
Yes, Admin removed the 2.1 file for me yesterday.
