### ISSUE TITLE
Error on initial setup

### ISSUE THREAD

**Issue by SavageWarrior** [eshapard/AnkiHabitica#75]
I get this error after entering my User ID and API token.

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.12 (380d59f7) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
  File "C:\Users\James\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 276, in setup
    save_stats(None, None)
  File "C:\Users\James\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 191, in save_stats
    json.dump(ah.config, open(ah.conffile, 'w'))
<class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'C:\\Users\\James\\AppData\\Roaming\\Anki2\\addons21\\1758045507\\user_files\\AnkiHabitica.conf'

**Comment by eshapard** [comment]
It's saying that it can't find the AnkiHabitica.conf file which should
be in a user_files subdirectory where the addon is installed.

Is that file there? Did you run the setup option after insalling the
addon?

Does this error occur immediately on starting Anki, or after you start
reviewing cards?

Quoting SavageWarrior (2019-06-07 08:11:43)

**Comment by SavageWarrior** [comment]
That file isn't there. The error occurs when I am trying to run the setup option. I enter my User ID and App token, hit enter, then it appears.
