### ISSUE TITLE
No option to edit on Linux

### ISSUE THREAD

**Issue by calypsomatic** [eshapard/AnkiHabitica#76]
I think this may be because I am on Linux, but when I follow the directions on the wiki to change the settings, (Tools >> Add-ons >> ankihabitica >> ....) there is no option to Edit.  There is a 'Config' button, but when I select that, a pop-up appears that says "Add-on has no configuration."  I am using Anki version 2.1.5.  Am I correct that this is a Linux issue, and can it be fixed?

**Comment by 71e6fd52** [comment]
Thanks for your issue. I didn't switch to Anki 2.1 configuration feature yet. You need edit source file yourself for now.
