### ISSUE TITLE
Freeze on point scoring

### ISSUE THREAD

**Issue by edoreld** [eshapard/AnkiHabitica#78]
I use Anki with a mobile phone plan. I've now reached the limit of my mobile phone plan and will have a very slow connection until the end of the month. 

So, onto my issue. Whenever I complete a flashcard that will trigger a point score, if I am tethered through this slow mobile connection, Anki will just freeze. There will be no apparent scoring or message like "No Internet connection available". It simply freezes. On my Mac, I see the spinning beachball of doom. I am then forced to force quit the application and restart it. 

I've pinpointed the problem to AnkiHabitica by disabling and enabling the addon.

I've delved through the code and have had some success by changing the timeout on the internet checking function from 10 to 3. 

However, sometimes the application freezes for longer than that. I think that what is happening is that AnkiHabitica detects that there is an internet connection - albeit a poor one - and then it tries to earn points. It's in scoring the points that it freezes for some time if the connection is too slow. 

I can see a few solutions to this problem:

1. Add a setting to allow the addon to only score when exiting/starting Anki (so check_internet always returns false). This solves the problem if blocage during reviews, though of course the problem can also appear when exiting/entering Anki.

2. Make the earn_points function asynchronous. This has the advantage that the program won't freeze at all! Players get a notification, if notifications are enabled, and point scoring gets done in the background. If the upload fails in the background, the points will be scored as if the internet connection was down.

**Comment by 71e6fd52** [comment]
If earn is asynchronous, the time to pop up the earn success message is not appropriate.
