### ISSUE TITLE
Quicker "Ok" pressing on pop up window?

### ISSUE THREAD

**Issue by Z1839** [eshapard/AnkiHabitica#79]
Big fan of the addon.

I wanted to suggest allowing the "Ok" button on the "Huzzah!" window to be always automatically highlighted so that I can just press it to select "Ok".

I find that pressing the space bar doesn't select it, and I have to use my mouse to click it. Also, perhaps even an option to either don't have the window show at all, or make it more like a quick popup that fades (Like puppy reinforcement"

**Comment by 71e6fd52** [comment]
There already an option to disable the window, "show_popup".

**Comment by 71e6fd52** [comment]
Did space work in 2.1.5?

**Comment by eshapard** [comment]
I never had to use the mouse for this. But I can't remember if I hit 
'space' or 'enter'... this may be OS specific. Have you tried hitting 
'enter'?

Excerpts from Z1839's message of August 30, 2019 10:24 am:
