### ISSUE TITLE
Progress Bar Not Updating/Frozen  

### ISSUE THREAD

**Issue by shlee24** [eshapard/AnkiHabitica#81]
Hi! I love this add-on very much and it worked for me for 2 months until recently I'm not sure what happened but the progress bar on Anki 2.0 stopped updating so no matter how many cards I did, the progress bar and the HP/Exp/Mana numbers stayed frozen. I've tried restarting Anki, deleting and re-downloading the add-on, re-inputing the user and API codes, but everything has just stayed frozen (there isn't even an error code or notification). 

I would really love to know if there is a way to fix this!

**Comment by eshapard** [comment]
Try deleting the habit on habitica or editing it's contents to delete 
the date ankihabitica stores there. What you're describing sounds like a 
problem that will be fixed by that.

Excerpts from shlee24's message of October 5, 2019 10:41 am:

**Comment by shlee24** [comment]
THANK YOU SO MUCH IT WORKED!
