### ISSUE TITLE
Suggest to add proxy support

### ISSUE THREAD

**Issue by nlfiasel** [eshapard/AnkiHabitica#83]
There are some regions can't visit habitica directly. As for me, I set a http proxy at localhost:8118. 
Access through the proxy is simple by changing the code below.

https://github.com/eshapard/AnkiHabitica/blob/09be43194752d2c42aeccc827788a7ce225bae51/AnkiHabitica/habitica_api.py#L60

to

```
# Proxy
proxy = '127.0.0.1:8118'
proxy_handler = urllib.request.ProxyHandler({
      'http': 'http://' + proxy,
      'https': 'https://' + proxy
      })
handler = urllib.request.HTTPSHandler(context=context)
opener = urllib.request.build_opener(proxy_handler,handler)
urllib.request.install_opener(opener)
response = json.load(urllib.request.urlopen(req, timeout=timeout))
```

I hope that the plugin can directly implement similar functions. But I don't quite understand the setting logic of the configuration file. 

Thank you very much for your efforts in this plugin.

**Comment by 71e6fd52** [comment]
Thank you to give me the implement detail.

As far as I know, https can use http proxy well, and not all proxy support https, might below code work better?

```
proxy_handler = urllib.request.ProxyHandler({
      'http': proxy,
      'https': proxy
})
```

**Comment by nlfiasel** [comment]
Yes, it works well. Thank you very much!
