### ISSUE TITLE
error after starting anki

### ISSUE THREAD

**Issue by ZengShuyuan** [eshapard/AnkiHabitica#92]
Firstly, I'd like to thank you for this add on.

I installed this add on a few days ago. It has worked perfectly till today I received this error after starting anki. The add on is still working when I review my cards. So maybe this is not a severe error. I leave the debug info here jsut in case, error are not good after all.

thank you in advance!

>Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1
>
>Unhandled exception in thread started by <bound method Habitica.check_anki_habit_task of <1758045507.habitica_class.Habitica object at 0x0000022B0B037780>>
Caught exception:
  File "C:\Users\lenovo\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 288, in check_anki_habit_task
    self.hrpg_showInfo("Your %s habit is not configured correctly yet.\nPlease set it to Up only and Mental attribute." % habit)
<class 'NameError'>: name 'habit' is not defined

**Comment by 71e6fd52** [comment]
Did you change the habit setting in Habitica, which should set to Up only and Mental attribute?
