### ISSUE TITLE
Popup still shows when no internet

### ISSUE THREAD

**Issue by Z1839** [eshapard/AnkiHabitica#98]
I disabled the popup message as shown in the tutorial. However, I noticed that when my internet is disconnected, I still get the popup that says "unable to score points" etc. and press ok.

**Comment by 71e6fd52** [comment]
Only popups after scoring can be disabled. AnkiHabitica can't work without the internet. You can disable AnkiHabitica and score the backlog when connected to the internet.

Any PR making AnkiHabitica work offline is welcome.
